// <auto-generated />
using System;
using FootballManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FootballManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FootballManagerDbContext))]
    partial class FootballManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FootballManager.Domain.Entities.AcademyPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<int>("Attack")
                        .HasColumnType("integer")
                        .HasColumnName("attack");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Defense")
                        .HasColumnType("integer")
                        .HasColumnName("defense");

                    b.Property<int>("DevelopmentProgress")
                        .HasColumnType("integer")
                        .HasColumnName("development_progress");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("first_name");

                    b.Property<int>("Fitness")
                        .HasColumnType("integer")
                        .HasColumnName("fitness");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("last_name");

                    b.Property<int>("Morale")
                        .HasColumnType("integer")
                        .HasColumnName("morale");

                    b.Property<int>("Passing")
                        .HasColumnType("integer")
                        .HasColumnName("passing");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("position");

                    b.Property<int>("Potential")
                        .HasColumnType("integer")
                        .HasColumnName("potential");

                    b.Property<string>("TrainingFocus")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("training_focus");

                    b.HasKey("Id");

                    b.HasIndex("ClubId", "LastName", "FirstName");

                    b.ToTable("academy_players", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<decimal>("TransferBudget")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("transfer_budget");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "Name")
                        .IsUnique();

                    b.ToTable("clubs", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.FinanceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("description");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entry_type");

                    b.HasKey("Id");

                    b.HasIndex("ClubId", "OccurredAt");

                    b.ToTable("finance_entries", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Fixture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwayClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_club_id");

                    b.Property<int?>("AwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HomeClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_club_id");

                    b.Property<int?>("HomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals");

                    b.Property<bool>("IsPlayed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_played");

                    b.Property<DateTime?>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.HasKey("Id");

                    b.HasIndex("AwayClubId");

                    b.HasIndex("HomeClubId");

                    b.HasIndex("SeasonId", "RoundNumber", "HomeClubId", "AwayClubId")
                        .IsUnique();

                    b.ToTable("fixtures", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Formation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Defenders")
                        .HasColumnType("integer")
                        .HasColumnName("defenders");

                    b.Property<int>("Forwards")
                        .HasColumnType("integer")
                        .HasColumnName("forwards");

                    b.Property<int>("Midfielders")
                        .HasColumnType("integer")
                        .HasColumnName("midfielders");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("formations", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.GameSave", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastSavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_saved_at");

                    b.Property<string>("SaveName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("save_name");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<Guid>("SelectedClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_club_id");

                    b.HasKey("Id");

                    b.HasIndex("LastSavedAt");

                    b.HasIndex("SeasonId")
                        .IsUnique();

                    b.HasIndex("SelectedClubId");

                    b.ToTable("game_saves", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_template");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Lineup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FormationId")
                        .HasColumnType("uuid")
                        .HasColumnName("formation_id");

                    b.Property<Guid>("GameSaveId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_save_id");

                    b.Property<string>("StarterPlayerIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("starter_player_ids");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.HasIndex("GameSaveId")
                        .IsUnique();

                    b.ToTable("lineups", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<int>("Attack")
                        .HasColumnType("integer")
                        .HasColumnName("attack");

                    b.Property<int>("AttributeProgress")
                        .HasColumnType("integer")
                        .HasColumnName("attribute_progress");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Defense")
                        .HasColumnType("integer")
                        .HasColumnName("defense");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("first_name");

                    b.Property<int>("Fitness")
                        .HasColumnType("integer")
                        .HasColumnName("fitness");

                    b.Property<int>("InjuryMatchesRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("injury_matches_remaining");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_captain");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("last_name");

                    b.Property<int>("Morale")
                        .HasColumnType("integer")
                        .HasColumnName("morale");

                    b.Property<int>("Passing")
                        .HasColumnType("integer")
                        .HasColumnName("passing");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("position");

                    b.Property<int>("SquadNumber")
                        .HasColumnType("integer")
                        .HasColumnName("squad_number");

                    b.HasKey("Id");

                    b.HasIndex("ClubId", "SquadNumber")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer")
                        .HasColumnName("current_round");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "Name")
                        .IsUnique();

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<decimal>("Fee")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("fee");

                    b.Property<Guid>("FromClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_club_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid>("ToClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_club_id");

                    b.HasKey("Id");

                    b.HasIndex("FromClubId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ToClubId");

                    b.ToTable("transfers", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.AcademyPlayer", b =>
                {
                    b.HasOne("FootballManager.Domain.Entities.Club", "Club")
                        .WithMany("AcademyPlayers")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Club", b =>
                {
                    b.HasOne("FootballManager.Domain.Entities.League", "League")
                        .WithMany("Clubs")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.FinanceEntry", b =>
                {
                    b.HasOne("FootballManager.Domain.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Fixture", b =>
                {
                    b.HasOne("FootballManager.Domain.Entities.Club", "AwayClub")
                        .WithMany()
                        .HasForeignKey("AwayClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballManager.Domain.Entities.Club", "HomeClub")
                        .WithMany()
                        .HasForeignKey("HomeClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballManager.Domain.Entities.Season", "Season")
                        .WithMany("Fixtures")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayClub");

                    b.Navigation("HomeClub");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.GameSave", b =>
                {
                    b.HasOne("FootballManager.Domain.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballManager.Domain.Entities.Club", "SelectedClub")
                        .WithMany()
                        .HasForeignKey("SelectedClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("SelectedClub");
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Lineup", b =>
                {
                    b.HasOne("FootballManager.Domain.Entities.Formation", "Formation")
                        .WithMany("Lineups")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballManager.Domain.Entities.GameSave", "GameSave")
                        .WithOne("Lineup")
                        .HasForeignKey("FootballManager.Domain.Entities.Lineup", "GameSaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");

                    b.Navigation("GameSave");
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Player", b =>
                {
                    b.HasOne("FootballManager.Domain.Entities.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Season", b =>
                {
                    b.HasOne("FootballManager.Domain.Entities.League", "League")
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Transfer", b =>
                {
                    b.HasOne("FootballManager.Domain.Entities.Club", "FromClub")
                        .WithMany()
                        .HasForeignKey("FromClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballManager.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballManager.Domain.Entities.Club", "ToClub")
                        .WithMany()
                        .HasForeignKey("ToClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromClub");

                    b.Navigation("Player");

                    b.Navigation("ToClub");
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Club", b =>
                {
                    b.Navigation("AcademyPlayers");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Formation", b =>
                {
                    b.Navigation("Lineups");
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.GameSave", b =>
                {
                    b.Navigation("Lineup");
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.League", b =>
                {
                    b.Navigation("Clubs");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("FootballManager.Domain.Entities.Season", b =>
                {
                    b.Navigation("Fixtures");
                });
#pragma warning restore 612, 618
        }
    }
}
